/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.interfaces;

import com.example.modelo.Cliente;
import com.example.modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author caco
 */
public class frmPrincipal extends javax.swing.JFrame {

    private Cliente client2;
    private static String nome;
    private static List<Usuario> usuarios = new ArrayList<>();

    public frmPrincipal() {
        initComponents();
        setFont();

        
        client2 = new Cliente(JOptionPane.showInputDialog("Digite o endereco IP do servidor"));
        
        setApelido("Digite seu nome: ");
        client2.getMensagemToPanel(principal);
    }

    public void setApelido(String msg) {
        String text = JOptionPane.showInputDialog(msg);
        if (text != null && text.length() > 3) {
            nome = text;
            client2.sendMensagem(text);
        } else {
            setApelido("Um nome deve ser inserido: ");
        }
    }

    public void setFont() {
        try {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("NotoColorEmoji-Regular.ttf")));
        } catch (IOException | FontFormatException e) {
            // Handle exception
        }
    }

    public void sendMensagem(){
        if (txfTexto.getText().startsWith("/nick ")){
            String novoNome = txfTexto.getText().split(" ", 2)[1]; 
            if (novoNome != null && novoNome.length() > 3){
                nome = novoNome;
            }
        }

        client2.sendMensagem(txfTexto.getText() + " ");
        txfTexto.setText("");
        txfTexto.requestFocus();

    }

    public static void addMensagem(String[] info, JPanel panel) {
        Mensagem msg = new Mensagem();

        msg.setTexto(info[1]);
        int numero = -1;
        GridBagConstraints c = new GridBagConstraints(0, GridBagConstraints.RELATIVE, 1, 1, 1.0, 0.0,
                GridBagConstraints.LINE_START, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0);

        if (info[0].equals(nome)) {
            numero = 7;
            msg.setBackground(new Color(189, 147, 249));
            c.anchor = GridBagConstraints.LINE_END;
        } else {

            for (Usuario usuario : usuarios) {
                if (usuario.getNome().equals(info[0])) {

                    numero = usuario.getColorNumber();
                    break;
                }
            }
            if (numero == -1) {
                Random rand = new Random();
                numero = rand.nextInt(7);
                Usuario usuario = new Usuario(info[0], numero);
                usuarios.add(usuario);
            }
        }

        msg.setTitulo(info[0], numero);
        panel.add(msg, c);

        panel.revalidate();
        panel.repaint();

    }

    public static void addNota(String nota, JPanel panel) {
        Nota msg = new Nota();

        msg.setTexto(nota);

        GridBagConstraints c = new GridBagConstraints(0, GridBagConstraints.RELATIVE, 1, 1, 1.0, 0.0,
                GridBagConstraints.CENTER, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0);

        panel.add(msg, c);

        panel.revalidate();
        panel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        principal = new javax.swing.JPanel();
        txfTexto = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        jScrollBar1.setBlockIncrement(100);
        jScrollBar1.setUnitIncrement(100);
        jScrollBar1.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App");
        setBackground(new java.awt.Color(68, 71, 90));
        setMinimumSize(new java.awt.Dimension(780, 600));
        setPreferredSize(new java.awt.Dimension(756, 550));

        jPanel1.setBackground(new java.awt.Color(68, 71, 90));
        jPanel1.setMinimumSize(new java.awt.Dimension(756, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(756, 550));

        jScrollPane1.setBackground(new java.awt.Color(98, 114, 164));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(600, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 400));
        jScrollPane1.setVerticalScrollBar(jScrollBar1);

        principal.setBackground(new java.awt.Color(40, 42, 54));
        java.awt.GridBagLayout principalLayout = new java.awt.GridBagLayout();
        principalLayout.columnWidths = new int[] {0, 5, 0};
        principalLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        principal.setLayout(principalLayout);
        jScrollPane1.setViewportView(principal);

        txfTexto.setBackground(new java.awt.Color(40, 42, 54));
        txfTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txfTexto.setForeground(new java.awt.Color(248, 248, 242));
        txfTexto.setToolTipText("Digite aqui...");
        txfTexto.setCaretColor(new java.awt.Color(248, 248, 242));
        txfTexto.setMargin(new java.awt.Insets(2, 12, 2, 6));
        txfTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTextoActionPerformed(evt);
            }
        });

        btnEnviar.setBackground(new java.awt.Color(98, 114, 164));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(248, 248, 242));
        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfTexto)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnviarActionPerformed
        sendMensagem();
    }// GEN-LAST:event_btnEnviarActionPerformed

    private void txfTextoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txfTextoActionPerformed
        sendMensagem();
    }// GEN-LAST:event_txfTextoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel principal;
    private javax.swing.JTextField txfTexto;
    // End of variables declaration//GEN-END:variables
}
