/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.interfaces;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author caco
 */
public class Mensagem extends javax.swing.JPanel {

    private List<Color> colors = new ArrayList<>();

    public Mensagem() {
        initComponents();
        initColors();
    }

    public void initColors() {
        colors.add(new Color(139, 233, 253));
        colors.add(new Color(80, 250, 123));
        colors.add(new Color(255, 184, 108));
        colors.add(new Color(255, 121, 198));
        colors.add(new Color(189, 147, 249));
        colors.add(new Color(255, 85, 85));
        colors.add(new Color(241, 250, 140));
        colors.add(new Color(68, 71, 90));

    }

    public void setTitulo(String titulo, int colorNumber) {
        Border etborder = BorderFactory.createEtchedBorder();
        TitledBorder border = BorderFactory.createTitledBorder(etborder, titulo);
        border.setTitleColor(colors.get(colorNumber));
        this.setBorder(border);
    }

    public void setTexto(String texto) {
        lblTexto.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTexto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(68, 71, 90));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "teste",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        lblTexto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTexto.setForeground(new java.awt.Color(248, 248, 242));
        lblTexto.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(lblTexto, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
