/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.example.interfaces;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author caco
 */
public class Nota extends javax.swing.JPanel {

    /**
     * Creates new form mensagem
     */
    public Nota() {
        initComponents();
    }

    public void setTitle(String title) {
        Border etborder = BorderFactory.createEtchedBorder();
        TitledBorder border = BorderFactory.createTitledBorder(etborder, title);
        border.setTitleColor(Color.yellow);
        this.setBorder(border);
    }

    public void setTexto(String texto) {
        lblTexto.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTexto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(98, 114, 164));
        setLayout(new java.awt.GridBagLayout());

        lblTexto.setBackground(new java.awt.Color(2, 242, 242));
        lblTexto.setForeground(new java.awt.Color(248, 248, 242));
        lblTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        add(lblTexto, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
